branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

git:
  depth: 10
dist: trusty
sudo: required

matrix:
  include:
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t phylozoom_frontend .
        - docker images
        - docker tag phylozoom_frontend $DOCKER_ORGANIZATION/phylozoom_frontend
        - docker push $DOCKER_ORGANIZATION/phylozoom_frontend
      on:
        branch: master
