git:
  depth: 10
dist: trusty
sudo: required

matrix:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t phylozoom-frontend .
      - docker images
      - docker tag phylozoom-frontend $DOCKER_USERNAME/phylozoom-frontend
      - docker push $DOCKER_USERNAME/phylozoom-frontend
