version: '3'
services:
  api:
    image: 'bcbi/phylozoom-api'
    ports:
      - "8089:8089"
  frontend:
    image: 'bcbi/phylozoom-frontend'
    ports:
      - "8080:8080"
    depends_on:
      - "api"
